In [1]:
import numpy as np

In [2]:
array_list = np.array([1, 2, 3, 4, 5])
array_list

array([1, 2, 3, 4, 5])

In [3]:
array_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones_array = np.ones((3, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# np.arange(start, stop, step) : Syntaxe
seq_array = np.arange(0, 10, 2)
seq_array

array([0, 2, 4, 6, 8])

In [8]:
# Tableau de valeurs aléatoires entre 0 et 1.
rand_array = np.random.random((2, 3))
rand_array

array([[0.06422193, 0.93961502, 0.85920059],
       [0.58398077, 0.074079  , 0.91655462]])

In [9]:
# Affichage du troisième élément
access_array = np.array([1, 2, 3, 4, 5])
access_array[2]

3

In [20]:
step_array = np.array([3, 2, 8, 4, 11])
step_array[::2]

array([ 3,  8, 11])

In [11]:

access_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
access_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
access_matrix[1, 2]

6

In [13]:
# Affichage de [2, 3]
slice_array = np.array([1, 2, 3, 4, 5])
slice_array[1:3]

array([2, 3])

In [23]:
slice_matrix = np.array([
                    [1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]
                ])
                
slice_matrix[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [24]:
# Modification
edit_array = np.array([3, 2, 8, 4, 11])
edit_array[2] = 10
edit_array

array([ 3,  2, 10,  4, 11])

In [25]:
edit_matrix = np.array([
                    [1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]
                ])
                
edit_matrix[0:2, 1:3] = [[20, 30], [50, 60]]
edit_matrix

array([[ 1, 20, 30],
       [ 4, 50, 60],
       [ 7,  8,  9]])

In [31]:
# Tableau de 0 à 9 que nous segmentons
# en trois parts égales
div_array = np.arange(9)
np.split(div_array, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [32]:
# Vecteur de 1 à 12
shp_array = np.arange(1, 13)

# Transformation vecteur en matrice
reshp_array = shp_array.reshape((3, 4))

# Affichage matrice
reshp_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
sqrt_array = np.arange(1, 13, 3)
# Affichage du vecteur créé
sqrt_array

array([ 1,  4,  7, 10])

In [38]:
# Affichage de la racine carrée des valeurs du vecteur
np.sqrt(sqrt_array)

array([1.        , 2.        , 2.64575131, 3.16227766])

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a - b)

[-3 -3 -3]


In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)

[ 4 10 18]


In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a / b)

[0.25 0.4  0.5 ]


In [43]:
np.mean(a)

2.0

In [45]:
np.std(a)

0.816496580927726

In [46]:
np.sum(a)

6

In [47]:
np.max(a)

3

In [49]:
ops_array = np.array([
                    [11, 21, 43], 
                    [42, 54, 69], 
                    [37, 48, 59]
                ])

In [50]:
np.mean(ops_array)

42.666666666666664

In [51]:
ops_array = np.array([
                    [11, 21, 43], 
                    [42, 54, 69], 
                    [37, 48, 59]
                ])

np.std(ops_array)

17.068489485989478

In [52]:
ops_array = np.array([
                    [11, 21, 43], 
                    [42, 54, 69], 
                    [37, 48, 59]
                ])

np.max(ops_array)

69